package nl.reproducer.resources;

public class ExampleDocuments {


    public static final String XML =

        "<ns1:registrationRequest xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:ns=\"http://www.broservices.nl/xsd/brocommon/3.0\" xmlns:ns1=\"http://www.broservices.nl/xsd/issfr/2.0\" xmlns:ns2=\"http://www.opengis.net/gml/3.2\" xmlns:ns3=\"http://www.broservices.nl/xsd/sfrcommon/2.0\">\n"
            + "         <ns:requestReference>requestReference</ns:requestReference>\n"
            + "         <ns:deliveryAccountableParty>27376655</ns:deliveryAccountableParty>\n"
            + "         <ns:qualityRegime>IMBRO</ns:qualityRegime>\n"
            + "         <ns1:sourceDocument>\n"
            + "            <ns1:SFR_CompleteReport_V1 ns2:id=\"sfr\">\n"
            + "               <ns1:objectIdAccountableParty>TC-1_Registration</ns1:objectIdAccountableParty>\n"
            + "               <ns1:deliveryContext codeSpace=\"urn:bro:sfr:DeliveryContext\">publiekeTaak</ns1:deliveryContext>\n"
            + "               <ns1:surveyPurpose codeSpace=\"urn:bro:sfr:SurveyPurpose\">bodemchemischOnderzoek</ns1:surveyPurpose>\n"
            + "               <ns1:discipline codeSpace=\"urn:bro:sfr:Discipline\">bodemkunde</ns1:discipline>\n"
            + "               <ns1:fieldworkDate>\n"
            + "                  <ns:date>0101-01-01</ns:date>\n"
            + "               </ns1:fieldworkDate>\n"
            + "               <ns1:litterLayerInvestigated>nee</ns1:litterLayerInvestigated>\n"
            + "               <ns1:deliveredLocation>\n"
            + "                  <ns3:location>\n"
            + "                     <ns2:Point ns2:id=\"locationa339ebe0-4bed-4542-b7fc-b272873811af\" srsName=\"urn:ogc:def:crs:EPSG::28992\">\n"
            + "                        <ns2:pos>134750.000 477800.000</ns2:pos>\n"
            + "                     </ns2:Point>\n"
            + "                  </ns3:location>\n"
            + "                  <ns3:horizontalPositioningDate>\n"
            + "                     <ns:date>0101-01-01</ns:date>\n"
            + "                  </ns3:horizontalPositioningDate>\n"
            + "                  <ns3:horizontalPositioningMethod codeSpace=\"urn:bro:sfr:HorizontalPositioningMethod\">GPS200tot1000cm</ns3:horizontalPositioningMethod>\n"
            + "               </ns1:deliveredLocation>\n"
            + "               <ns1:deliveredVerticalPosition>\n"
            + "                  <ns3:localVerticalReferencePoint codeSpace=\"urn:bro:sfr:LocalVerticalReferencePoint\">maaiveld</ns3:localVerticalReferencePoint>\n"
            + "                  <ns3:offset uom=\"m\">0</ns3:offset>\n"
            + "                  <ns3:verticalDatum codeSpace=\"urn:bro:sfr:VerticalDatum\">NAP</ns3:verticalDatum>\n"
            + "                  <ns3:verticalPositioningDate>\n"
            + "                     <ns:date>1950-01-01</ns:date>\n"
            + "                  </ns3:verticalPositioningDate>\n"
            + "                  <ns3:verticalPositioningMethod codeSpace=\"urn:bro:sfr:VerticalPositioningMethod\">RTKGPS4tot10cm</ns3:verticalPositioningMethod>\n"
            + "               </ns1:deliveredVerticalPosition>\n"
            + "               <ns1:soilUncovering>\n"
            + "                  <ns3:SoilUncovering ns2:id=\"SoilUncovering\">\n"
            + "                     <ns3:endDepthSoilFace uom=\"m\">0</ns3:endDepthSoilFace>\n"
            + "                     <ns3:soilFaceOrientation uom=\"deg\">0</ns3:soilFaceOrientation>\n"
            + "                     <ns3:outcropType codeSpace=\"urn:bro:sfr:OutcropType\">afgraving</ns3:outcropType>\n"
            + "                  </ns3:SoilUncovering>\n"
            + "               </ns1:soilUncovering>\n"
            + "               <ns1:siteCharacteristic>\n"
            + "                  <ns3:SiteCharacteristic ns2:id=\"SiteCharacteristic\">\n"
            + "                     <ns3:soilUse codeSpace=\"urn:bro:sfr:SoilUse\">akkerAardappelen</ns3:soilUse>\n"
            + "                     <ns3:artificialDrainage codeSpace=\"urn:bro:sfr:ArtificialDrainage\">drainageAanwezig</ns3:artificialDrainage>\n"
            + "                     <ns3:positionOnGroundBody codeSpace=\"urn:bro:sfr:PositionOnGroundBody\">geen</ns3:positionOnGroundBody>\n"
            + "                     <ns3:surfaceLevelShifted codeSpace=\"urn:bro:sfr:SurfaceLevelShifted\">geegaliseerd</ns3:surfaceLevelShifted>\n"
            + "                     <ns3:tracesOfChurningPresent>nee</ns3:tracesOfChurningPresent>\n"
            + "                  </ns3:SiteCharacteristic>\n"
            + "               </ns1:siteCharacteristic>\n"
            + "               <ns1:soilFaceDescription>\n"
            + "                  <ns3:SoilFaceDescription ns2:id=\"SoilFaceDescription\">\n"
            + "                     <ns3:descriptionReportDate>\n"
            + "                        <ns:date>0101-01-01</ns:date>\n"
            + "                     </ns3:descriptionReportDate>\n"
            + "                     <ns3:descriptionProcedure codeSpace=\"urn:bro:sfr:DescriptionProcedure\">DescriptionProcedure</ns3:descriptionProcedure>\n"
            + "                     <ns3:describedWidth uom=\"m\">3.33</ns3:describedWidth>\n"
            + "                     <ns3:artificiallyHumidified>nee</ns3:artificiallyHumidified>\n"
            + "                     <ns3:fractionDistributionDetermined>ja</ns3:fractionDistributionDetermined>\n"
            + "                     <ns3:lowerBoundarySandFraction codeSpace=\"urn:bro:sfr:LowerBoundarySandFraction\">LowerBoundarySandFraction</ns3:lowerBoundarySandFraction>\n"
            + "                     <ns3:soilProfile>\n"
            + "                        <ns3:SoilProfile ns2:id=\"SoilProfile\">\n"
            + "                           <ns3:descriptionQuality codeSpace=\"urn:bro:sfr:DescriptionQuality\">DescriptionQuality</ns3:descriptionQuality>\n"
            + "                           <ns3:rootableDepthReached>nee</ns3:rootableDepthReached>\n"
            + "                           <ns3:meanHighestGroundwaterLevelReached>onbekend</ns3:meanHighestGroundwaterLevelReached>\n"
            + "                           <ns3:horizonRepetition>nee</ns3:horizonRepetition>\n"
            + "                           <ns3:localPhenomenon codeSpace=\"urn:bro:sfr:LocalPhenomenon\">LocalPhenomenon</ns3:localPhenomenon>\n"
            + "                           <ns3:sequenceDisturbed>ja</ns3:sequenceDisturbed>\n"
            + "                           <ns3:compactionPresent>ja</ns3:compactionPresent>\n"
            + "                           <ns3:soilLayer>\n"
            + "                              <ns3:SoilLayer ns2:id=\"SoilLayer\">\n"
            + "                                 <ns3:upperBoundary uom=\"m\">-0.08</ns3:upperBoundary>\n"
            + "                                 <ns3:upperBoundaryDetermination codeSpace=\"urn:bro:sfr:BoundaryPositioningMethod\">BoundaryPositioningMethod</ns3:upperBoundaryDetermination>\n"
            + "                                 <ns3:lowerBoundary uom=\"m\">0</ns3:lowerBoundary>\n"
            + "                                 <ns3:lowerBoundaryDetermination codeSpace=\"urn:bro:sfr:BoundaryPositioningMethod\">BoundaryPositioningMethod</ns3:lowerBoundaryDetermination>\n"
            + "                                 <ns3:lowerBoundaryShape codeSpace=\"urn:bro:sfr:BoundaryShape\">BoundaryShape</ns3:lowerBoundaryShape>\n"
            + "                                 <ns3:layerDiscontinuous>nee</ns3:layerDiscontinuous>\n"
            + "                                 <ns3:anthropogenic>ja</ns3:anthropogenic>\n"
            + "                                 <ns3:soilLife codeSpace=\"urn:bro:sfr:SoilLife\">SoilLife</ns3:soilLife>\n"
            + "                                 <ns3:rooted>ja</ns3:rooted>\n"
            + "                                 <ns3:slant>nee</ns3:slant>\n"
            + "                              </ns3:SoilLayer>\n"
            + "                           </ns3:soilLayer>\n"
            + "                        </ns3:SoilProfile>\n"
            + "                     </ns3:soilProfile>\n"
            + "                     <ns3:soilClassification>\n"
            + "                        <ns3:SoilClassification ns2:id=\"SoilClassification\">\n"
            + "                           <ns3:codeGroup codeSpace=\"urn:bro:sfr:CodeGroup\">CodeGroup</ns3:codeGroup>\n"
            + "                           <ns3:classificationCode>classificationCode</ns3:classificationCode>\n"
            + "                           <ns3:specialFeatureTop codeSpace=\"urn:bro:sfr:SpecialFeatureTop\">SpecialFeatureTop</ns3:specialFeatureTop>\n"
            + "                           <ns3:soilClass codeSpace=\"urn:bro:sfr:SoilClass\">SoilClass</ns3:soilClass>\n"
            + "                           <ns3:reworkingClass codeSpace=\"urn:bro:sfr:ReworkingClass\">ReworkingClass</ns3:reworkingClass>\n"
            + "                           <ns3:groundwaterTableClass codeSpace=\"urn:bro:sfr:GroundwaterTableClass\">GroundwaterTableClass</ns3:groundwaterTableClass>\n"
            + "                           <ns3:specialFeatureSite codeSpace=\"urn:bro:sfr:SpecialFeatureSite\">SpecialFeatureSite</ns3:specialFeatureSite>\n"
            + "                           <ns3:specialFeatureBottom>\n"
            + "                              <ns3:specialFeature codeSpace=\"urn:bro:sfr:SpecialFeature\">SpecialFeature</ns3:specialFeature>\n"
            + "                           </ns3:specialFeatureBottom>\n"
            + "                        </ns3:SoilClassification>\n"
            + "                     </ns3:soilClassification>\n"
            + "                  </ns3:SoilFaceDescription>\n"
            + "               </ns1:soilFaceDescription>\n"
            + "               <ns1:researchReportDate>\n"
            + "                  <ns:date>0101-01-01</ns:date>\n"
            + "               </ns1:researchReportDate>\n"
            + "            </ns1:SFR_CompleteReport_V1>\n"
            + "         </ns1:sourceDocument>\n"
            + "      </ns1:registrationRequest>";
}
